export {default as DesSkill} from "./DesSkill"
export {default as DevSkill} from "./DevSkill"
export {default as NetSkill} from "./NetSkill"
export {default as Skill} from "./Skill"
export {default as Skills} from "./Skills"
export {default as SocialMedia} from "./SocialMedia"
export {default as TypoMe} from "./TypoMe"